### ISSUE TITLE
[feature request] Combine Multiselect with autocomplete

### ISSUE THREAD

**Issue by morocarlo** [DharmeshPipariya/md2#2]
It is possible to combine multiselect with autocomplete?

`<md2-multiselect [items]="items"
            autocomplete="true"
            [item-text]="'name'"
            [(ngModel)]="item"
            (change)="selected($event)"
            placeholder="Placeholder Text">
</md2-multiselect>`

**Comment by DharmeshPipariya** [comment]
We have already created [md2-tags](https://github.com/DharmeshPipariya/md2/tree/master/src/components/tags) component, please refer it.
