### ISSUE TITLE
Can compilerOptions->target be changed to ES5?

### ISSUE THREAD

**Issue by james-hu** [dharmeshpipariya/md2#3]
Currently ES6 is used by md2 for generating .js files for distribution. 
According to this document: https://angular.io/docs/ts/latest/guide/typescript-configuration.html , Angular2 applications are suggested to use ES5 as the target.

I am using ES5 as the target of my Angular2 application. While testing the application, I got this error message:
`
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at (path to my project directory)/karma-test-shim.js:62009 <- webpack:///~/md2/src/components/select/select.js:11:0
`
I guess that is because select.js is targeted to ES6.

**Comment by james-hu** [comment]
well, I now use babel-loader to load those files and it works. So changing to ES5 may not be very important or urgent.

**Comment by DharmeshPipariya** [comment]
ok, we will update it soon...

**Comment by dharmeshpipariya** [comment]
We have updated ES5 you can use source code from `dev` branch or use `npm install md2@0.0.1-es5`.
