### ISSUE TITLE
Compile component to ES5

### ISSUE THREAD

**Issue by omararturo** [dharmeshpipariya/md2#4]
Hello, first of all, congratulate them for the work they are doing.

I 'm looking for solutions.
I 'm developing an app with meteor - angular2 - typescript , but when trying to use these components ( MD2 ) leave some numbers example : // 215 // 216 // 217 around all components and css styles are not loaded .
And is the cause of the problem is they have written their comoponentes using ES6 and new quotes ``. You could compile your components to ES5 as does @justindujardin https://github.com/justindujardin/ng2-material ? Any other solution.

Thank you

**Comment by DharmeshPipariya** [comment]
ok, we are trying to convert our library from ES6 to ES5, we will update it soon...

**Comment by morocarlo** [comment]
any news?

**Comment by dharmeshpipariya** [comment]
We have updated ES5 you can use source code from `dev` branch or use `npm install md2@0.0.1-es5`.

**Comment by omararturo** [comment]
EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on Md2Select

**Comment by dharmeshpipariya** [comment]
please use [tag@0.0.1-es5](https://github.com/dharmeshpipariya/md2/releases/tag/0.0.1-es5) it's working perfectly.

**Comment by dharmeshpipariya** [comment]
i have converted my full repo in ES5, you can check it on [https://github.com/Promact/md2](https://github.com/Promact/md2)
