### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by morocarlo** [dharmeshpipariya/md2#5]
on tags.ts you have to update the filterMatches and reset the query lastIndex each time

private filterMatches(query: RegExp) {
    let tempList = this._tags.map((tag: any) => new Tag(tag, this.textKey, this.valueKey));
    this.list = tempList.filter((t: Tag) => (query.test(t.text) && !this.items.find((i: Tag) => t.text === i.text)));
    if (this.list.length > 0) {
      this.focusedTag = 0;
    }
  }

query.lastIndex= 0;

this is how i have fixed the code:
`private filterMatches(query: RegExp) {
    let tempList = this._tags.map((tag: any) => new Tag(tag, this.textKey, this.valueKey));

    //this.list = tempList.filter((t: Tag) => (query.test(t.text) && !this.items.find((i: Tag) => t.text === i.text)));
      this.list = new Array();
      for (let t of tempList){
          query.lastIndex= 0;
          var res = query.test(t.text);
          if (res){
              this.list.push(t);
          }
      }
    if (this.list.length > 0) {
      this.focusedTag = 0;
    }
  }
`

**Comment by dharmeshpipariya** [comment]
Thanks @morocarlo for the code optimization, we'll check and update it.
