### ISSUE TITLE
md2-select not working on firefox

### ISSUE THREAD

**Issue by nelaturuk** [dharmeshpipariya/md2#6]
Hi, 

I am using md2 library for forms in an application. Below is the sample code for the select. 
It works perfectly in chrome. Could anyone help me undertsand if i am missing something to make it work in firefox

<md2-select id="tes" (change)="onChange($event)" formControlName="year">
                            <md2-option *ngFor="let vehYear of vehYears" [value]="vehYear.value" [selected]="vehYear.value==vehicleInfo.year">{{vehYear.label}}</md2-option>
                        </md2-select>

**Comment by dharmeshpipariya** [comment]
we have fixed this issue and published it with release @0.0.12
