### ISSUE TITLE
data-table pagination don't work correct 

### ISSUE THREAD

**Issue by romanoks** [dharmeshpipariya/md2#7]
Hello, 

md2-rows: When we change select list 'Rows per page'  and then change page number, we will see not correct count rows. For example. Change 'Rows per page' on 5 rows and choose page number 2. We don't see 5 rows on page, we will see more then 15 rows. This you will see in demo application

**Comment by dharmeshpipariya** [comment]
we have updated it on [https://github.com/promact/md2](https://github.com/promact/md2)
