### ISSUE TITLE
Information on md2-select for angular 2.4.x versions 

### ISSUE THREAD

**Issue by AngularTx** [dharmeshpipariya/md2#8]
We are planning to use Angular 2.4.7 version and the application will be used in IE browser only . 
I am looking for a select dropdown feature from a 3rd party resource . The IE select drop feature doesnot look good , 

So does your package work well on IE browser(ie 10 + ) ?
When displaying data in the select drop down can we pass data of any interface object type OR is there any standard way of dealing with it in this package ?
(Eg : I might have an object with many properties and, one of the property values would be used for the drop down values. and on select I could pass the whole object to the backend )

**Comment by dharmeshpipariya** [comment]
@AngularTx MD2 supports the most recent two versions of all major browsers: Chrome (including Android), Firefox, Safari (including iOS), and IE11 / Edge now we are targeting Latest browsers, so it is working in EDGE and IE11
